T04
RaaneshKumar/Training pull request #6
Opened 2023-08-09 09:51 UTC by RaaneshKumar

2023-08-26 11:47 UTC, rajeevramanTMM requested changes

2023-08-26 11:47 UTC, rajeevramanTMM commented on Program.cs
> +Console.Write ("Enter the first number: ");
Fix these errors.
![image](https://github.com/RaaneshKumar/Training/assets/94427955/bbc9f6e9-c48a-4efd-a20e-346319bc1626)
![image](https://github.com/RaaneshKumar/Training/assets/94427955/baeb3f5e-27db-4b78-849e-a581fa8d0b38)

2023-08-26 11:47 UTC, rajeevramanTMM commented on Program.cs
> +int[] multiples = new int[] { };
change this to list. Here you are creating a new array for each and every append which is not correct.

2023-09-11 09:23 UTC, rajeevramanTMM requested changes

2023-09-11 09:23 UTC, rajeevramanTMM commented on Program.cs
> +if (num1 == true && num2 == true) {
No need to explicitly check a bool with true. if (num1 && num2) is enough.

2023-09-11 09:23 UTC, rajeevramanTMM commented on Program.cs
> +   if (number1 == 0) Console.WriteLine ($"LCM of given numbers is 0. \nGCD of given numbers is {number2}.");
Here you are checking number1 with zero. Is this is expected output which I have shared in the image?
![image](https://github.com/RaaneshKumar/Training/assets/94427955/b1dd5cc2-2d1f-4a68-8dac-e81df92b5a4e)

2023-09-11 09:23 UTC, rajeevramanTMM commented on Program.cs
> +         int lcm1 = number1 % i; int lcm2 = number2 % i;
No need lcm1 and lcm2 you can compare the operation inside if statement itself. It has only one instance of it.

2023-09-11 09:23 UTC, rajeevramanTMM commented on Program.cs
> +      int lcm = (number1 * number2) / gcd;
lcm is one instance can you change?.

2023-09-15 09:05 UTC, RaaneshKumar commented on Program.cs
> +   if (number1 == 0) Console.WriteLine ($"LCM of given numbers is 0. \nGCD of given numbers is {number2}.");
Yes, this is the expected output.

2023-09-18 15:53 UTC, closed without merging